[2024-06-24T13:54:24.797+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T13:54:24.846+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T13:54:24.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T13:54:24.870+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T13:54:24.888+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): inaccurate> on 2024-06-23 00:00:00+00:00
[2024-06-24T13:54:24.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=635) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T13:54:24.909+0000] {standard_task_runner.py:63} INFO - Started process 637 to run task
[2024-06-24T13:54:24.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpqmd41ldj']
[2024-06-24T13:54:24.915+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask inaccurate
[2024-06-24T13:54:25.064+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2024-06-23T00:00:00+00:00 [running]> on host bdf37b3fc48d
[2024-06-24T13:54:25.286+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-24T13:54:25.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T13:54:25.313+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-24T13:54:25.315+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-06-24T13:54:25.343+0000] {subprocess.py:86} INFO - Output:
[2024-06-24T13:54:25.354+0000] {subprocess.py:93} INFO - inaccurate
[2024-06-24T13:54:25.355+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-24T13:54:25.358+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T13:54:25.410+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240624T135424, end_date=20240624T135425
[2024-06-24T13:54:25.474+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T13:54:25.536+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T13:54:25.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
